### ISSUE TITLE
iOS Build

### ISSUE THREAD

**Issue by wishmehdeath** [marchellodev/sharik#18]
I cannot build for iOS 
Sharik Wrapper not found

**Comment by marchellodev** [comment]
Sorry about that, there are some complications with calling golang code form ios.
Unfortunately, I do not have an access to a mac computer, so I cannot fix this issue right now.

However, you could try building the `v3` branch, since it has no dependency on `sharik_wrapper`. But keep in mind that Sharik on this branch does not work properly yet, so i'd recommend you to use the version from the AppStore :)
If you have any problems with `v3`, please remove folder `ios` and run `flutter create .`

**Comment by marchellodev** [comment]
This should be fixed now, since we are not relying on the Wrapper anymore. Thanks!
