### ISSUE TITLE
Telegram Group

### ISSUE THREAD

**Issue by mubashir-rehman** [marchellodev/sharik#28]
Kindly create a telegram group for discussion and better communication with users.

**Comment by marchellodev** [comment]
Are you sure there is a demand for that? :D

**Comment by mubashir-rehman** [comment]
There isn't a demand but you will get more recognition and it is easy to understand what is needed for the project.

**Comment by marchellodev** [comment]
Ok, thanks for the idea!
I plan to seriously start working on this project soon, that's when I'll probably create a chat

**Comment by EchedeyLR** [comment]
Why not in the Matrix network since Telegram is propietary in server side and not federated.

**Comment by mubashir-rehman** [comment]
@EchedeyLR Telegram has a lot of audience but it was just a suggestion mainly because I got the link from their.

**Comment by naDevi** [comment]
@marchellodev one more vote for matrix and you can run mastodon acc if necessary to post sharik updates.
I think that's no problem about audience; normally only fan become aware about that (not advertise), otherhand here has this repo for report bugs, FRs.

**Comment by marchellodev** [comment]
Hey, I have enabled [Discussions](https://github.com/marchellodev/sharik/discussions) on GitHub. I am not going to create a Telegram or a Matrix chat since not everyone is familiar with those apps. Also, I do not think that presence of the chat in one of those apps will make Sharik more popular :)

Speaking of posting updates, I've been thinking of creating a twitter account, where I would post stats, updates, and talk with you guys. While i understand that Twitter is not an amazing website, it is very accessible and easy to use.

So, if you want to talk about anything, welcome to Discussions :) I am probably going to create a twitter account when Sharik v3 will be ready.

Thank you all! Please feel free to reopen this issue if you have something to add :)
