### ISSUE TITLE
Lightweight

### ISSUE THREAD

**Issue by zcraber** [marchellodev/sharik#33]
I know this is not a big deal but is it possible to make the app more lightweight?
For e.g. [WiFi File Transfer](https://play.google.com/store/apps/details?id=com.smarterdroid.wififiletransfer) app is just under 500 KB.

**Comment by marchellodev** [comment]
Hey!

Thanks for such a great question! The next version of Sharik is going to weight much less than it weights now (~11mb) due to removed dependency on Golang. I hope it wouldn't be more than 8mb. However, I am afraid I am not going to be able to make it even smaller. Sharik is not a native app, it was developed using [Flutter](https://flutter.dev/) (in order to make it pretty and cross-platform), which adds in size to the final build and there is nothing I can do about it.

If you have any more questions or maybe have any ideas on decreasing the app's size, please feel free to reopen this issue
