### ISSUE TITLE
Cannot launch application on manjaro

### ISSUE THREAD

**Issue by Mikaka27** [marchellodev/sharik#58]
Hi,

I installer this app from snap store, however it fails to launch.
When I run it from command line I get this:
```
[mikaka@stacjonarny ~]$ snap run sharik-app
creating glfw window: APIUnavailable: EGL: Library not found
```

**Comment by marchellodev** [comment]
Thanks for opening the issue!

As far as I understand, snap apps run in a virtual environment that contains all the required dependencies. Therefore, either the package that is required for the app to work on your system is not included in the environment, or your system is missing some packages. Please take a look at [this page ](https://bbs.archlinux.org/viewtopic.php?id=221519) (the first google result on this error, seems like `pacman -Syu mesa` might fix the issue)

By the way, do you use X as a window server? I have not tested the app on wayland at all yet :)

Also, the Snap version of the app was put together based on trial and error (since there were no official docs on packaging go-flutter apps), and was only tested on debian-based systems. The newer version (which I hope to release soon) will be packaged based on official flutter guidelines, so this problem will be mitigated probably.

For now, I would suggest trying to install the package that the link above recommends. If this does not work, you can always download .zip version of the app and create a .desktop file or a symlink :)

**Comment by marchellodev** [comment]
If none of that helps, please feel free to reopen the issue.
