### ISSUE TITLE
Question: What is ackee.mark.vin

### ISSUE THREAD

**Issue by heberjeur** [marchellodev/sharik#77]
I know that sharik is a local file transfer software, I also know that it respects the personnal data, so what is ackee.mark.vin and is it necessary to download fonts?
![Screenshot_20210630-212609_NetGuard_1](https://user-images.githubusercontent.com/11852634/124027872-a3018c00-d9f3-11eb-955f-21fb102ee4ea.jpg)

**Comment by marchellodev** [comment]
Hey, thanks for the question!

`ackee.mark.vin` is a link to an ackee software installed on my personal server. It is used for analytics, and you can read more about it in the [tracking_policy.md](https://github.com/marchellodev/sharik/blob/master/tracking_policy.md) document. BTW, before the v3 we used Google Analytics, but have decided to migrate to ackee to be more privacy-friendly.

Now speaking of fonts, we are using google fonts repo, as it is very comfortable to use. Sharik is focused on supporting as many languages as possible, and most of the time, languages require specific fonts to look properly. Therefore, as the translation count will keep growing, it is not the a great idea to package all the fonts into the binaries at the expense of their sizes. Also, fonts are being downloaded as they are needed, which minimizes the storage that the app occupies, and decreases the number of requests to google servers.

On top of that, as far as I understand, all that google sees are your ip adress and the name of the font you are trying to download. One of the solution would be pre-downloading those fonts on my server, and using it instead of fonts.google.com, however, I do not think that this is necessary.

Also, as far as I remember, Sharik needs the internet connectivity to connect to GitHub to fetch the CHANGELOG.md file. But again, all that the GitHub sees are the ip adress and the location of the CHANGELOG file.

Thank you again. I'll close the issue for now. Please let me know if you have any other questions :)

**Comment by marchellodev** [comment]
btw, that software is that? :)

**Comment by heberjeur** [comment]
thanks for your response ,I will use trebleshot that does not use any trackers or loggers methods
