### ISSUE TITLE
[Bug] Some of the texts are not translated

### ISSUE THREAD

**Issue by skarpheta** [marchellodev/sharik#98]
**Phone:** MRD-LX1 (Huawei Y6 2019)
**Android version:** 9.0
**App version:** 3.0.0

**Bug:**
"Send", "Receive" and "Files" are not translated to other languages even if they are translated on Crowdin. Though I'm not sure if new version is on the Crowdin.

**Comment by marchellodev** [comment]
Oh, I'm so sorry. Actually, this small update (of the receive and send button) was not supposed to be in v3. I have mistakenly added it to v3 release for F-droid to pick up. Since it's just on F-droid, and there are icons along text, I don't think it is necessary to revert the change, and release a new version

Thanks!
